name = "lean_book"
version = "0.1.0"
defaultTargets = ["LeanBook"]

[leanOptions]
autoImplicit = false
warningAsError = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "5c8398df528176d9c87ccd9226ba8f7c8852d59c"

[[lean_lib]]
name = "LeanBook"
